name: Monitoramento Diario
on:
  schedule:
    - cron: '0 12 * * *' # Executa todos os dias às 12:00 UTC
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v3
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Instalar dependencias
      run: |
        pip install playwright pandas openpyxl pypdf requests
        playwright install chromium
    - name: Executar Script
      run: python seu_script.py
